name: CI

on:
  pull_request:
    branches: "*"
  push:
    branches: master
  schedule:
    - cron: "0 7 * * 1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - crystal_version: 1.0.0
            DB: mysql
            db_user: root
            db_password:
          - crystal_version: 1.0.0
            DB: postgres
            db_user: dbuser
            db_password: dbpassword
          - crystal_version: 1.1.0
            DB: mysql
            db_user: root
            db_password:
          - crystal_version: 1.1.0
            DB: postgres
            db_user: dbuser
            db_password: dbpassword
          - crystal_version: 1.2.2
            DB: mysql
            db_user: root
            db_password:
          - crystal_version: 1.2.2
            DB: postgres
            db_user: dbuser
            db_password: dbpassword
          - crystal_version: 1.3.2
            DB: mysql
            db_user: root
            db_password:
          - crystal_version: 1.3.2
            DB: postgres
            db_user: dbuser
            db_password: dbpassword
          - crystal_version: 1.4.1
            DB: mysql
            integration: true
            linter: true
            db_user: root
            db_password:
          - crystal_version: 1.4.1
            DB: postgres
            integration: true
            linter: true
            db_user: dbuser
            db_password: dbpassword
          - crystal_version: 1.4.1
            DB: postgres
            db_user: dbuser
            db_password: dbpassword
            other: MT=1
          - crystal_version: 1.4.1
            DB: postgres
            pair: true
            db_user: dbuser
            db_password: dbpassword
            other: PAIR_DB_USER=root PAIR_DB_PASSWORD=
          - crystal_version: 1.4.1
            DB: mysql
            pair: true
            db_user: root
            db_password:
            other: PAIR_DB_USER=dbuser PAIR_DB_PASSWORD=dbpassword
          - DB: postgres
            db_user: dbuser
            db_password: dbpassword
            crystal_version: nightly

    runs-on: ubuntu-latest

    env:
      DB: ${{ matrix.DB }}
      PAIR: ${{ matrix.pair }}
      DB_USER: ${{ matrix.db_user }}
      DB_PASSWORD: ${{ matrix.db_password }}

    steps:
      - name: Export rest variables
        run: export ${{ matrix.other }}

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{matrix.crystal_version}}

      - name: Donwload sources
        uses: actions/checkout@v2

      - name: Check formatting
        if: ${{ matrix.linter }}
        run: make format

      - name: Install dependencies
        run: |
          function version { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }
          if [ $(version '${{ matrix.crystal_version }}') -lt $(version '1.4.1') ]; then
            cp .github/shard_1_3_2.yml shard.yml
          fi
          shards install

      - name: Run linter
        if: ${{ matrix.linter }}
        run: make lint

      - name: 'Install MySQL'
        if: ${{ matrix.DB == 'mysql' || matrix.pair }}
        run: bash .github/setup_mysql.sh

      - name: Install PostgreSQL
        if: ${{ matrix.DB == 'postgres' || matrix.pair }}
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: '12'
          postgres_user: ${{ env.DB_USER }}
          postgres_password: ${{ env.DB_PASSWORD }}

      - name: Create configuration file
        run: bash ./scripts/setup.sh .github/database.yml

      - name: Run migrations
        run: make sam db:setup

      - name: Run specs
        run: |
          if [ $MT == '1' ]
          then
            crystal spec -Dpreview_mt
          else
            crystal spec --error-trace
          fi

      - name: Run integration specs
        if: ${{ matrix.integration }}
        run: bash .github/run_integration_tests.sh
